"""empty message

Revision ID: 60109a6eae5d
Revises: 
Create Date: 2020-08-17 22:28:18.971876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60109a6eae5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CUSTOMER',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cName', sa.Unicode(length=30), nullable=False),
    sa.Column('customerType', sa.CHAR(length=30, collation='Arabic_CI_AS'), nullable=True),
    sa.Column('maxCredit', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('PRODUCT',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('pName', sa.Unicode(length=30), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('ORDER1',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('oDate', sa.DateTime(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['CUSTOMER.cid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('ORDERITEM',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['ORDER1.oid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid'], ['PRODUCT.pid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iid')
    )
    op.create_table('OrderTotal',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('totalAmount', sa.BigInteger(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['ORDER1.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderTotal')
    op.drop_table('ORDERITEM')
    op.drop_table('ORDER1')
    op.drop_table('PRODUCT')
    op.drop_table('CUSTOMER')
    # ### end Alembic commands ###
